sudo: required
language: go
go:
    - tip
    
notifications:
    email: false

services:
  - docker
  
before_install:
- docker pull sebp/elk
- docker run -d -p 7777:9200 -p 5601:5601 sebp/elk
- docker ps -a

install:
  - go get github.com/Sirupsen/logrus
  - go get gopkg.in/olivere/elastic.v5
  - travis_wait 2