sudo: true
language: go
go:
    - tip
    
notifications:
    email: false

services:
  - docker
  
before_script:
  - sudo sysctl -w vm.max_map_count=262144

before_install:
- docker pull sebp/elk
- docker run -d -p 7777:9200 -p 5601:5601 --name elk sebp/elk
- docker logs elk

install:
  - go get github.com/sirupsen/logrus
  - go get gopkg.in/olivere/elastic.v5
  - travis_wait 5
